# Generated by Django 5.2.10 on 2026-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_lead_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
